/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module add_5 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] result;
  
  always @* begin
    if (alufn[0+1-:2] == 1'h0) begin
      result = a + b;
    end else begin
      if (alufn[0+1-:2] == 1'h1) begin
        result = a - b;
      end else begin
        result = a * b;
      end
    end
    out = result;
    if (result == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    n = result[15+0-:1];
    v = (a[15+0-:1] & (alufn[0+0-:1] ^ b[15+0-:1]) & ~result[15+0-:1]) | (~a[15+0-:1] & ~(alufn[0+0-:1] ^ b[15+0-:1]) & result[15+0-:1]);
  end
endmodule
