/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_7 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn[1+1-:2])
      1'h1: begin
        out = {15'h0000, (a == b)};
      end
      2'h2: begin
        out = {15'h0000, (a < b)};
      end
      2'h3: begin
        out = {15'h0000, (a <= b)};
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
